Add a PPA repository for installing a newer version of Git
This is needed because of:

The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Error: Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH.

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>